### ISSUE TITLE
Namespaced attributes

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [Hugobros3/shady#21]
I'd put things like `descriptor_set` or `descriptor_binding` in a `vcc` or `shady` namespace.

**Comment by Hugobros3** [comment]
Yes that's indeed welcome for C++. For C however I would keep it like this.

**Comment by Hugobros3** [comment]
Did a first draft of this idea in https://github.com/Hugobros3/shady/commit/bec77d9b6e5b8e4afb3a6216d30e16831a8e470d.

**Comment by devshgraphicsprogramming** [comment]
looks good
