### ISSUE TITLE
Feature request: Add a `#define` to disambiguate Vcc from `__cplusplus` and `__clang__`

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [Hugobros3/shady#22]
WASM has `__EMSCRIPTEN__` what do you have?

**Comment by Hugobros3** [comment]
I'll likely use `__SHADY__` or `__VCC__` or similar.

**Comment by Hugobros3** [comment]
Added `__SHADY__` in https://github.com/Hugobros3/shady/commit/38c4678d4b3d55699069b8b36803d191c2ea6df4
